app/Http/Controllers/Manager/CauHoiThuongGapController.php, app/Http/Controllers/Manager/ToChucController.php, app/Http/Controllers/Manager/TuyenDungController.php, app/Http/Requests/CauHoiThuongGapRequest.php, app/Http/Requests/ToChucRequest.php, app/Http/Requests/TuyenDungRequest.php, app/cau_hoi_thuong_gap.php, app/tuyen_dung.php, database/migrations/2017_06_25_140026_create_table_cauhoithuonggap.php, database/migrations/2017_06_25_140212_create_table_tuyendung.php, resources/views/admin/manager_data/cau_hoi_thuong_gap/create.blade.php, resources/views/admin/manager_data/cau_hoi_thuong_gap/edit.blade.php, resources/views/admin/manager_data/cau_hoi_thuong_gap/index.blade.php, resources/views/admin/manager_data/to_chuc/create.blade.php, resources/views/admin/manager_data/to_chuc/edit.blade.php, resources/views/admin/manager_data/to_chuc/index.blade.php, resources/views/admin/manager_data/tuyen_dung/create.blade.php, resources/views/admin/manager_data/tuyen_dung/edit.blade.php, resources/views/admin/manager_data/tuyen_dung/index.blade.php, routes/admin.php
=> to chuc,tuyen dung, cau thuong gap

resources/views/admin/index.blade.php, resources/views/admin/layout/admin_layout.blade.php, resources/views/admin/manager_data/su_kien/create.blade.php, resources/views/admin/manager_data/su_kien/edit.blade.php, resources/views/admin/manager_data/su_kien/index.blade.php
=> fix sidebar su_kien

app/Http/Controllers/Manager/CongNgheController.php, resources/views/admin/manager_data/cong_nghe/edit.blade.php, resources/views/admin/manager_data/cong_nghe/index.blade.php, resources/views/admin/manager_data/loai_tin/edit.blade.php, resources/views/admin/manager_data/tin_tuc/edit.blade.php, routes/admin.php
Sửa lại pathEdit cho các mục chuyen-gia, loai-tin, tin-tuc.
=> Sua them path js cho cong-nghe, loai-tin va tin-tuc

resources/views/admin/manager_data/doi_tac/index.blade.php
=> change image

app/Http/Controllers/Manager/ChuyenGiaController.php, app/Http/Controllers/Manager/CongNgheController.php, resources/views/admin/manager_data/chuyen_gia/create.blade.php, resources/views/admin/manager_data/chuyen_gia/edit.blade.php, resources/views/admin/manager_data/cong_nghe/create.blade.php, resources/views/admin/manager_data/cong_nghe/edit.blade.php
Sửa một số lỗi hiển thị sau test
=> fix loi sau test phan chuyen-gia va cong-nghe

app/Http/Controllers/PageController/PageController.php, public/pages/css/faq.css, public/pages/css/news.css, public/pages/js/faq.js, resources/views/pages/cauhoithuonggap.blade.php, resources/views/pages/details_tintuc.blade.php, resources/views/pages/layout/index-lienhe.blade.php, routes/web.php
=> sua giao dien details, them faq

resources/views/pages/details_tintuc.blade.php
=> Details new

app/CauHoi.php, app/CauHoiTranslation.php, app/Http/Controllers/Manager/CauHoiThuongGapController.php, app/Http/Requests/CauHoiThuongGapRequest.php, database/migrations/2017_06_28_102323_create_cau_hoi_thuong_gap_table.php, database/migrations/2017_06_28_102422_create_cau_hoi_thuong_gap_translation_table.php, resources/views/admin/manager_data/cau_hoi_thuong_gap/create.blade.php, resources/views/admin/manager_data/cau_hoi_thuong_gap/edit.blade.php, resources/views/admin/manager_data/cau_hoi_thuong_gap/index.blade.php
=> hoan thien cau hoi thuong gap

app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/Auth/RegisterController.php, app/Mail/EmailVerification.php, app/User.php, database/migrations/2014_10_12_000000_create_users_table.php, database/seeds/UserTableSeeder.php, resources/views/auth/Register.blade.php, resources/views/auth/login.blade.php, resources/views/emails/verification.blade.php, routes/admin.php, routes/web.php
=> active after register

app/ActiveAccount.php, app/Http/Controllers/Auth/ActiveAccountController.php, app/Http/Controllers/Auth/RegisterController.php, database/migrations/2017_07_06_084834_create_active_accounts_table.php, public/pages/css/custom.css, resources/views/admin/manager_data/user/create.blade.php, resources/views/admin/manager_data/user/edit.blade.php, resources/views/auth/ActiveAccount.blade.php, resources/views/auth/EmailActiveAccount.blade.php, resources/views/auth/error_token.blade.php, resources/views/emails/verification.blade.php
=> ative account after register

app/Http/Controllers/Manager/LoaiDoiTacController.php, resources/views/admin/layout/admin_layout.blade.php, resources/views/admin/manager_data/loai_doi_tac/create.blade.php, resources/views/admin/manager_data/loai_doi_tac/edit.blade.php, resources/views/admin/manager_data/loai_doi_tac/index.blade.php, routes/admin.php
=> doi-tac && loai-doi-tac

app/Http/Controllers/Manager/CongNgheController.php, resources/views/admin/manager_data/cong_nghe/create.blade.php, resources/views/admin/manager_data/cong_nghe/edit.blade.php, resources/views/admin/manager_data/cong_nghe/index.blade.php
=> CongNgheTran

resources/views/admin/manager_data/cau_hoi_thuong_gap/create.blade.php, resources/views/admin/manager_data/cau_hoi_thuong_gap/edit.blade.php, resources/views/admin/manager_data/cau_hoi_thuong_gap/index.blade.php, resources/views/admin/manager_data/chuyen_gia/create.blade.php, resources/views/admin/manager_data/chuyen_gia/edit.blade.php, resources/views/admin/manager_data/chuyen_gia/index.blade.php, resources/views/admin/manager_data/cong_nghe/create.blade.php, resources/views/admin/manager_data/cong_nghe/edit.blade.php, resources/views/admin/manager_data/cong_nghe/index.blade.php, resources/views/admin/manager_data/loai_tin/create.blade.php, resources/views/admin/manager_data/loai_tin/edit.blade.php, resources/views/admin/manager_data/loai_tin/index.blade.php, resources/views/admin/manager_data/su_kien/create.blade.php, resources/views/admin/manager_data/su_kien/edit.blade.php, resources/views/admin/manager_data/su_kien/index.blade.php, resources/views/admin/manager_data/tin_tuc/create.blade.php, resources/views/admin/manager_data/tin_tuc/edit.blade.php, resources/views/admin/manager_data/tin_tuc/index.blade.php, resources/views/admin/manager_data/to_chuc/create.blade.php, resources/views/admin/manager_data/to_chuc/edit.blade.php, resources/views/admin/manager_data/to_chuc/index.blade.php, resources/views/admin/manager_data/tuyen_dung/create.blade.php, resources/views/admin/manager_data/tuyen_dung/edit.blade.php, resources/views/admin/manager_data/tuyen_dung/index.blade.php, resources/views/admin/manager_data/user/edit.blade.php
Chỉnh sửa đường dẫn tương đối trong admin
=> chinh sua duong dan tuong doi

app/Http/Controllers/Manager/CongNgheController.php, resources/views/admin/manager_data/cong_nghe/create.blade.php, resources/views/admin/manager_data/cong_nghe/edit.blade.php, resources/views/admin/manager_data/cong_nghe/index.blade.php
=> Cong nghe update

app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/PageController/PageController.php, public/pages/js/custom.js, resources/views/pages/layout/footer.blade.php, resources/views/pages/layout/header.blade.php
Reverts cuongvumanh/ntbic_home#46
=> Revert "locale in Home Page"

app/Http/Controllers/Manager/TuyenDungController.php, app/Http/Controllers/PageController/PageController.php, app/Http/Controllers/PageController/TuyenDungPageController.php, public/pages/css/detailsNew.css, resources/views/admin/manager_data/to_chuc/index.blade.php, resources/views/admin/manager_data/tuyen_dung/index.blade.php, resources/views/pages/layout/header.blade.php, resources/views/pages/tuyen_dung/index.blade.php, resources/views/pages/tuyen_dung/show.blade.php, resources/views/pages/tuyendung.blade.php, routes/web.php
sua tuyen dung.them ti tin tuc
=> dan link tuyen dung,sua cai cho tin tuc

public/pages/css/custom.css, resources/views/pages/layout/header.blade.php
=> edit header

resources/views/pages/layout/header.blade.php, routes/web.php
=> edit route

database/seeds/SuKien.php, resources/views/pages/tin_tuc/newsOfkind.blade.php, routes/web.php
=> sua tin tuc thuoc tung loai

app/HinhSidebar.php, app/Http/Controllers/Manager/AnhSideBarController.php, app/Http/Controllers/Manager/LogoDoiTacController.php, app/LogoDoiTac.php, database/migrations/2017_07_12_083019_create_logo_doi_tac_table.php, database/migrations/2017_07_12_083158_create_hinh_anh_sidebar_table.php, resources/views/admin/layout/admin_layout.blade.php, routes/admin.php
=> front-end sidebar and partner

resources/views/pages/su_kien/detailssukien.blade.php
=> sua details su kien

resources/views/pages/layout/footer.blade.php, resources/views/pages/trangchu.blade.php
=> edit footer

app/Http/Controllers/PageController/DoiTacController.php, app/Http/Controllers/PageController/SuKienController.php, app/Http/Controllers/PageController/TinTucController.php
=> them-sidebar

resources/views/pages/doi_tac/index.blade.php
=> them img res

resources/views/pages/layout/footer.blade.php
sua footer viet hoa chu GIOI THIEU
=> sua gioi thieu

app/Http/Controllers/Manager/LienHeController.php, app/Http/Requests/LienHeRequest.php, app/LienHe.php, resources/views/admin/manager_data/lien_he/index.blade.php, resources/views/pages/lienhe.blade.php, routes/admin.php
=> show lien he admin

app/Http/Controllers/PageController/LienHeController.php, app/Http/Controllers/PageController/PageController.php, app/Http/Controllers/PageController/TinTucController.php, app/Http/Requests/LienHeRequest.php, resources/views/pages/lienhe.blade.php, routes/web.php
=> submit lienhe

app/Http/Controllers/PageController/LienHeController.php
=> sua lien he controller

resources/views/admin/manager_data/tuyen_dung/edit.blade.php, resources/views/pages/tin_tuc/show.blade.php
=>  them link cho cai nut share like

public/pages/css/news.css
=> sua o cho show tintuc

resources/views/pages/su_kien/danhsachsukien.blade.php
=> edit view su kien

public/pages/css/custom.css, public/pages/css/news.css, resources/lang/en/footer.php, resources/lang/vi/footer.php, resources/views/pages/layout/footer.blade.php, resources/views/pages/layout/sidebar.blade.php, resources/views/pages/trangchu.blade.php
=>  sua tin noi bat

app/Http/Controllers/PageController/PageController.php, app/Http/Controllers/PageController/TinTucController.php
=> counter_tintuc
